apiVersion: apps/v1
kind: Deployment
metadata:
 name: jira
 namespace: atlassian
 labels:
  app.kubernetes.io/name: jira
  app.kubernetes.io/component: atlassian
spec:
 replicas: 1
 selector:
  matchLabels:
    app.kubernetes.io/name: jira
 template:
  metadata:
    labels:
      app.kubernetes.io/name: jira
  spec:
    terminationGracePeriodSeconds: 300
    initContainers:
        - name: jira-lockfile
          securityContext:
          image: busybox
          command: ['sh', '-c', 'rm -f /var/atlassian/application-data/jira/.jira-home.lock']
          volumeMounts:
            - mountPath: "/var/atlassian/application-data/jira/"
              name: jira-application-data
    containers:
      - name: jira-atlassian
        image: atlassian/jira-software:8.12.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: "6Gi"
        ports:
        - containerPort: 8080
        readinessProbe:
            httpGet:
              port: 8080
              path: /status
            initialDelaySeconds: 180
            periodSeconds: 15
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: jira-atlassian-config-db
        - configMapRef:
            name: jira-atlassian-config-server
        env:
         - name: ATL_JDBC_PASSWORD
           valueFrom:
              secretKeyRef:
               name: jira-database-passowrd
               key: dbpassword
        volumeMounts:
          - mountPath: "/var/atlassian/application-data/jira"
            name: jira-application-data
    volumes:
        - name: jira-application-data
          persistentVolumeClaim:
            claimName: jira-efs-claim
      
      