apiVersion: apps/v1
kind: Deployment
metadata:
 name: jira
 namespace: atlassian
 labels:
  app.kubernetes.io/name: jira
  app.kubernetes.io/component: atlassian
spec:
 replicas: 1
 selector:
  matchLabels:
    app.kubernetes.io/name: jira
 template:
  metadata:
    labels:
      app.kubernetes.io/name: jira
  spec:
    containers:
      - name: jira-atlassian
        image: atlassian/jira-software:7.13.13
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "128M"
          limits:
            cpu: "4"
            memory: "8Gi"
        ports:
        - containerPort: 8080
        readinessProbe:
            httpGet:
              port: 8080
              path: /status
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: jira-atlassian-config
        env:
         - name: ATL_JDBC_PASSWORD
           valueFrom:
              secretKeyRef:
               name: jira-database-passowrd
               key: dbpassword
        volumeMounts:
          - mountPath: "/var/atlassian/application-data/jira"
            name: jira-application-data
    volumes:
        - name: jira-application-data
          persistentVolumeClaim:
            claimName: jira-efs-claim
      
      