apiVersion: v1
kind: Service
metadata:
 namespace: jira
 name: jira-atlassian-service
 labels:
  app.kubernetes.io/name: jira
  app.kubernetes.io/component: atlassian
spec:
 type: LoadBalancer
 ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
 selector:
  app.kubernetes.io/name: jira
  app.kubernetes.io/component: atlassian
