apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: atlassian
  name: confluence-efs-claim
  labels:
    app.kubernetes.io/name: confluence
    app.kubernetes.io/component: atlassian
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi