apiVersion: v1
kind: Service
metadata:
 namespace: atlassian
 name: confluence-service
 labels:
  app.kubernetes.io/name: confluence
  app.kubernetes.io/component: atlassian
spec:
 type: NodePort
 ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP
 selector:
  app.kubernetes.io/name: confluence
