apiVersion: apps/v1
kind: Deployment
metadata:
 name: jira-atlassian
 labels:
  app: jira
spec:
 replicas: 1
 selector:
  matchLabels:
    app: jira
 template:
  metadata:
    labels:
      app: jira
  spec:
    containers:
      - name: jira-atlassian
        image: atlassian/jira-software:7.13.13
        ports:
        - containerPort: 8080
