apiVersion: v1
kind: Service
metadata:
 name: jira-atlassian-service
 labels:
  app: jira-service
spec:
 type: NodePort
 ports:
  - port: 31010
    nodePort: 31010
    protocol: TCP
    targetPort: 8080
 selector:
  app: jira
