---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: atlassian-k8s
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sauravpatar/atlassian-k8s
