apiVersion: v1
kind: ConfigMap
metadata:
  name: confluence-atlassian-config-db
  namespace: atlassian
  labels:
    app.kubernetes.io/name: confluence
    app.kubernetes.io/component: atlassian
data:
  JVM_MINIMUM_MEMORY: 3072m
  JVM_MAXIMUM_MEMORY: 10240m
  SET_PERMISSIONS: "true"
  ATL_JDBC_URL: jdbc:postgresql://db-confluence-atlassian.ctt9hc3po2iq.ap-south-1.rds.amazonaws.com:5432/postgres
  ATL_JDBC_USER: master
  ATL_DB_DRIVER: org.postgresql.Driver
  ATL_DB_TYPE: postgresql
  ATL_DB_SCHEMA_NAME: public
  ATL_DB_POOLMINSIZE: "20"
  ATL_DB_POOLMAXSIZE: "20"
  ATL_DB_MAXWAITMILLIS: "30000"
  ATL_DB_MAXIDLE: "20"
  ATL_DB_VALIDATIONQUERY: select 1
  ATL_DB_TIMEBETWEENEVICTIONRUNSMILLIS: "300000"
  ATL_DB_MINEVICTABLEIDLETIMEMILLIS: "60000"
  ATL_DB_REMOVEABANDONED: "true"
  ATL_DB_REMOVEABANDONEDTIMEOUT: "300"
  ATL_DB_TESTWHILEIDLE: "true"
  ATL_DB_TESTONBORROW: "false"