apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: atlassian
  name: jira-efs-pv
  labels:
    app.kubernetes.io/name: jira
    app.kubernetes.io/component: atlassian
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-223da6f3::fsap-02a8c2fe1a21ac259